version: '3.8'

services:
  my-postgres-db:
    build:
      dockerfile: dockerfile
    container_name: postgres-db
    env_file:
      - .env
    volumes:
      - my-postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

volumes:
  my-postgres_data: